name: Test GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set up Git user
        run: |
          git config user.name "ktc-hyunsoo"
          git config user.email "hyunsoo.woo@kt.com"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy React app to /app path
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: app

      - name: Deploy Storybook as default page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          cname: ktc-hyunsoo.github.io/testRepo
